name: eqmonitor
description: Earth Quake Monitor Application

publish_to: "none"

version: 0.4.1+201

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Control
  flutter_riverpod: ^1.0.4
  hooks_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  state_notifier: ^0.7.2+1
  # DB
  isar: ^3.0.0-dev.8
  path_provider: ^2.0.11
  isar_flutter_libs: ^3.0.0-dev.8
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  # Firebase
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_messaging: ^12.0.1
  firebase_auth: ^3.6.1
  firebase_performance: ^0.8.2+1
  firebase_analytics: ^9.3.0
  # Notificaiton
  awesome_notifications: ^0.6.21
  flutter_tts: ^3.5.0
  # API
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  oauth1: ^2.0.0
  # Map
  latlong2: ^0.8.1

  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  logger: ^1.1.0
  geojson: ^1.0.0
  image: ^3.2.0
  url_launcher: ^6.1.5
  html: ^0.15.0
  home_widget:
    git:
      url: https://github.com/josepedromonteiro/home_widget.git
  auto_size_text: ^3.0.0
  dart_twitter_api: ^0.5.6+1
  device_preview: ^1.1.0
  device_info_plus: ^4.0.1
  share_plus: ^4.0.10
  bordered_text: ^2.0.0

  flutter_native_splash: ^2.2.6
  csv: ^5.0.1
  supabase_flutter: ^0.3.3
  flutter_hooks: ^0.18.5+1
  fast_i18n: ^5.12.6
  collection: ^1.16.0
  dynamic_color: ^1.4.0
  adaptive_navigation: ^0.0.7
  settings_ui: ^2.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  pedantic_mono: ^1.19.2
  isar_generator: ^3.0.0-dev.8
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/intensity/
    - assets/kmoni/
    - assets/maps/
  fonts:
    - family: CaskaydiaCove
      fonts:
        - asset: fonts/Caskaydia_Cove_Nerd_Font_Mono.ttf

flutter_native_splash:
  #? flutter pub run flutter_native_splash:create
  color: "#011C30"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/icon.png

  # This property allows you to specify an image used as branding in the splash screen. It must be
  # a png file. Currently, it is only supported for Android and iOS.
  #branding: assets/dart.png

  # Specify your branding image for dark mode.
  #branding_dark: assets/dart_dark.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #
  # Make sure this content mode value should not be similar to android_gravity value and
  # ios_content_mode value.
  #branding_mode: bottom

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#222222"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

flutter_icons:
  #? flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#011C30"
  adaptive_icon_foreground: "assets/icon_foreground.png"
  remove_alpha_ios: true
