name: eqmonitor
description: Earth Quake Monitor Application

publish_to: "none"

version: 0.1.0+50

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  logger: ^1.1.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  firebase_messaging: ^11.2.6
  font_awesome_flutter: ^9.2.0
  ntp: ^2.0.0
  http: ^0.13.4
  intl: ^0.17.0
  sliding_up_panel: ^2.0.0+1
  geojson: ^1.0.0
  flutter_map: ^0.14.0
  syncfusion_flutter_maps: ^19.4.50-beta
  csv: ^5.0.1
  image: ^3.1.1
  firebase_performance: ^0.8.0+5
  firebase_app_check: ^0.0.6+5
  firebase_auth: ^3.3.7
  twitter_login: ^4.0.1
  settings_ui: ^2.0.2
  flutter_native_splash: ^2.0.4
  status_alert: ^1.0.0
  oauth1: ^2.0.0
  url_launcher: ^6.0.20
  cool_alert: ^1.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  package_info_plus: ^1.3.1
  awesome_notifications: ^0.6.21
  html: ^0.15.0
  solid_bottom_sheet: ^0.1.10
  home_widget: ^0.1.5
  shared_preferences: ^2.0.13
  supabase_flutter: ^0.2.12
  latlong2: ^0.8.1
  vector_map_tiles: ^1.4.3
  lat_lon_grid_plugin: ^0.2.2
  vector_tile_renderer: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_path_converter: ^1.0.1
  pedantic_mono: ^1.16.0
  flutter_launcher_icons: ^0.9.2
  flutter_flavorizr: ^2.1.2
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/japan.geojson
    - assets/icon.png
    - assets/light1.gif
    - assets/light2.gif
    - assets/intensity/
    - assets/map/0/0/
    - assets/map/1/1/
    - assets/map/10/860/
    - assets/map/10/861/
    - assets/map/10/862/
    - assets/map/10/863/
    - assets/map/10/864/
    - assets/map/10/865/
    - assets/map/10/866/
    - assets/map/10/867/
    - assets/map/10/868/
    - assets/map/10/869/
    - assets/map/10/870/
    - assets/map/10/871/
    - assets/map/10/872/
    - assets/map/10/873/
    - assets/map/10/874/
    - assets/map/10/875/
    - assets/map/10/876/
    - assets/map/10/877/
    - assets/map/10/878/
    - assets/map/10/879/
    - assets/map/10/880/
    - assets/map/10/881/
    - assets/map/10/882/
    - assets/map/10/883/
    - assets/map/10/884/
    - assets/map/10/885/
    - assets/map/10/886/
    - assets/map/10/887/
    - assets/map/10/888/
    - assets/map/10/889/
    - assets/map/10/890/
    - assets/map/10/891/
    - assets/map/10/892/
    - assets/map/10/893/
    - assets/map/10/894/
    - assets/map/10/895/
    - assets/map/10/896/
    - assets/map/10/897/
    - assets/map/10/898/
    - assets/map/10/899/
    - assets/map/10/900/
    - assets/map/10/901/
    - assets/map/10/902/
    - assets/map/10/903/
    - assets/map/10/904/
    - assets/map/10/905/
    - assets/map/10/906/
    - assets/map/10/907/
    - assets/map/10/908/
    - assets/map/10/909/
    - assets/map/10/910/
    - assets/map/10/911/
    - assets/map/10/912/
    - assets/map/10/913/
    - assets/map/10/914/
    - assets/map/10/915/
    - assets/map/10/916/
    - assets/map/10/917/
    - assets/map/10/918/
    - assets/map/10/919/
    - assets/map/10/920/
    - assets/map/10/921/
    - assets/map/10/922/
    - assets/map/10/923/
    - assets/map/10/924/
    - assets/map/10/925/
    - assets/map/10/926/
    - assets/map/10/927/
    - assets/map/10/928/
    - assets/map/10/929/
    - assets/map/10/930/
    - assets/map/10/931/
    - assets/map/10/932/
    - assets/map/10/933/
    - assets/map/10/934/
    - assets/map/10/935/
    - assets/map/10/936/
    - assets/map/2/3/
    - assets/map/3/6/
    - assets/map/3/7/
    - assets/map/4/13/
    - assets/map/4/14/
    - assets/map/5/26/
    - assets/map/5/27/
    - assets/map/5/28/
    - assets/map/5/29/
    - assets/map/6/53/
    - assets/map/6/54/
    - assets/map/6/55/
    - assets/map/6/56/
    - assets/map/6/57/
    - assets/map/6/58/
    - assets/map/7/107/
    - assets/map/7/108/
    - assets/map/7/109/
    - assets/map/7/110/
    - assets/map/7/111/
    - assets/map/7/112/
    - assets/map/7/113/
    - assets/map/7/114/
    - assets/map/7/115/
    - assets/map/7/116/
    - assets/map/7/117/
    - assets/map/8/215/
    - assets/map/8/216/
    - assets/map/8/217/
    - assets/map/8/218/
    - assets/map/8/219/
    - assets/map/8/220/
    - assets/map/8/221/
    - assets/map/8/222/
    - assets/map/8/223/
    - assets/map/8/224/
    - assets/map/8/225/
    - assets/map/8/226/
    - assets/map/8/227/
    - assets/map/8/228/
    - assets/map/8/229/
    - assets/map/8/230/
    - assets/map/8/231/
    - assets/map/8/232/
    - assets/map/8/233/
    - assets/map/8/234/
    - assets/map/9/430/
    - assets/map/9/431/
    - assets/map/9/432/
    - assets/map/9/433/
    - assets/map/9/434/
    - assets/map/9/435/
    - assets/map/9/436/
    - assets/map/9/437/
    - assets/map/9/438/
    - assets/map/9/439/
    - assets/map/9/440/
    - assets/map/9/441/
    - assets/map/9/442/
    - assets/map/9/443/
    - assets/map/9/444/
    - assets/map/9/445/
    - assets/map/9/446/
    - assets/map/9/447/
    - assets/map/9/448/
    - assets/map/9/449/
    - assets/map/9/450/
    - assets/map/9/451/
    - assets/map/9/452/
    - assets/map/9/453/
    - assets/map/9/454/
    - assets/map/9/455/
    - assets/map/9/456/
    - assets/map/9/457/
    - assets/map/9/458/
    - assets/map/9/459/
    - assets/map/9/460/
    - assets/map/9/461/
    - assets/map/9/462/
    - assets/map/9/463/
    - assets/map/9/464/
    - assets/map/9/465/
    - assets/map/9/466/
    - assets/map/9/467/
    - assets/map/9/468/


flutter_native_splash:
  #? flutter pub run flutter_native_splash:create
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#F1F4F9"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/icon.png

  # This property allows you to specify an image used as branding in the splash screen. It must be
  # a png file. Currently, it is only supported for Android and iOS.
  #branding: assets/dart.png

  # Specify your branding image for dark mode.
  #branding_dark: assets/dart_dark.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #
  # Make sure this content mode value should not be similar to android_gravity value and
  # ios_content_mode value.
  #branding_mode: bottom

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "##F1F4F9"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
