name: eqmonitor
description: An earthquake monitoring Application

publish_to: "none"

version: 2.0.0+1020

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_settings: ^4.2.0
  awesome_notifications: 0.7.4+1
  awesome_notifications_fcm: 0.7.4+1
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  dio_http2_adapter: ^2.2.0
  dynamic_color: ^1.6.5
  envied: ^0.3.0+3
  eqapi_schema:
    path: packages/eqapi_schema
  firebase_analytics: ^10.3.0
  firebase_core: ^2.11.0
  firebase_crashlytics: ^3.3.1
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_launcher_icons: ^0.13.0
  flutter_tts: ^3.6.3
  freezed_annotation: ^2.2.0
  geojson:
    git:
      url: git@github.com:FaFre/geojson.git
      ref: 7f0e305450014e264f6d0f5bf5b1a62501afc6c2
  go_router: ^7.0.0
  google_fonts: ^5.0.0
  hooks_riverpod: ^2.3.6
  image: ^4.0.17
  intl: ^0.17.0
  json_annotation: ^4.8.1
  native_shared_preferences: ^2.0.7
  ntp: ^2.0.0
  permission_handler: ^10.2.0
  retrofit: ^4.0.1
  retry: ^3.1.2
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.1
  sheet: ^1.0.0-pre
  socket_io_client: ^2.0.2
  talker_flutter: ^3.0.1
  vector_math: ^2.1.4
  web_socket_client: ^0.1.0-dev.3

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.4
  envied_generator: ^0.3.0+3
  flutter_gen_runner: ^5.3.1
  freezed: ^2.3.3
  go_router_builder: ^2.0.0
  json_serializable: ^6.6.2
  material_button_assist: ^1.0.0
  pedantic_mono: ^1.21.1
  retrofit_generator: ^6.0.0+3
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/kmoni/
    - assets/maps/
    - assets/fonts/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
