name: eqapi_schema
description: EQApi API Schema
version: 1.0.1
publish_to: "none"

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  collection: ^1.17.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  lat_lng:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/lat_lng

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  lints: ^2.1.1
  pedantic_mono: ^1.24.0
  test: ^1.24.7
