name: eqapi_schema
description: EQApi API Schema
version: 1.0.0

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.2
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  lints: ^2.0.0
  pedantic_mono: ^1.22.0
  test: ^1.21.0
