name: eqmonitor
description: An earthquake monitoring Application
publish_to: "none"

version: 2.4.0+1112

environment:
  sdk: ^3.3.0

dependencies:
  adaptive_dialog: ^2.0.0
  app_settings: ^5.1.1
  collection: ^1.17.1
  crypto: ^3.0.3
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  dynamic_color: ^1.7.0
  envied: ^0.5.3
  eqapi_client:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/eqapi_client
  eqapi_types:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/eqapi_types
  extensions:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/extensions
  firebase_analytics: ^10.7.0
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.4
  firebase_messaging: ^14.7.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_html: ^3.0.0-alpha.2
  flutter_local_notifications: ^17.0.0
  flutter_markdown: ^0.6.21
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^11.1.4
  google_fonts: ^6.2.1
  hooks_riverpod: ^3.0.0-dev.3
  image: ^4.1.7
  in_app_review: ^2.0.9
  intl: ^0.18.1
  jma_code_table_types:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/jma_code_table_types
  jma_map:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/jma_map
  jma_parameter_api_client:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/jma_parameter_api_client
  kyoshin_observation_point_types:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/kyoshin_observation_point_types
  lat_lng:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/lat_lng
  latlong2: ^0.9.0
  maplibre_gl:
    git:
      url: https://github.com/YumNumm/flutter-maplibre-gl.git
      ref: main
  ntp: ^2.0.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  purchases_flutter: ^6.25.0
  riverpod_annotation: ^3.0.0-dev.3
  screenshot: 2.1.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  sheet:
    git:
      url: https://github.com/YumNumm/modal_bottom_sheet.git
      branch: main
      path: sheet
  talker_dio_logger: ^2.4.0
  talker_flutter:
    git:
      url: https://github.com/Frezyx/talker.git
      branch: dev
      ref: 6425594b611b5f44ad88258cc97641ff96aba014
      path: packages/talker_flutter
  url_launcher: ^6.2.1
  uuid: ^4.3.3
  version: ^3.0.2
  web_socket_client: ^0.1.1
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.5.11
  dependency_validator: ^3.2.3
  envied_generator: ^0.5.2
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  pedantic_mono: ^1.24.0+1
  retrofit_generator: ^8.0.4
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  test: ^1.24.9
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/docs/

  shaders:
    - shaders/introduction.glsl

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
