name: Android CD

#発火条件
on:
  #ソースをmasterブランチにプッシュする時
  push:
    branches: [ main ]
  #他のブランチをmasterブランチにマッジする時
  pull_request:
    branches: [ main ]

jobs:
  build:
    #ビルド環境
    runs-on: ubuntu-latest

    steps:
      #リポジトリからソースをダンロード
      - uses: actions/checkout@v2
      #JAVA環境構築
      - name: install java 8.x
        uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      #Flutter環境構築
      - name: install flutter
        uses: subosito/flutter-action@v1
        with:
          #Flutterのバージョン
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: flutter dependencies install
        #ライブラリーの導入
        run: flutter pub get

      - name: build apk
        run: |
          echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > android/release.keystore
          export KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
          export KEY_ALIAS='${{ secrets.KEY_ALIAS }}'
          export KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
          flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk
