name: kyoshin_observation_point_converter_internal
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.1
  kyoshin_observation_point_types:
    git:
      url: https://github.com/YumNumm/EQMonitor.git
      path: packages/kyoshin_observation_point_types
  geojson_vi: ^2.2.4
  maps_toolkit: ^3.0.0
